PINECONE_ENV = "us-west1-gcp-free"
PINECONE_ENV_INFO_P1 = "us-west1-gcp"
PINECONE_INDEX_NAME = "hybrid-venue-search"
PINECONE_INDEX_NAME_BM25 = "hybrid-venue-bm25"
# SEMANTIC SEARCH MODEL DETAILS
MODEL_NAME = "sentence-transformers/all-mpnet-base-v2"
MODEL_NAME_NEW = "BAAI/bge-base-en-v1.5"
MODEL_NEW_INSTRUCTION = "Represent this sentence for searching relevant passages:"
NUM_CHUNK_IN_RESULTS = 200

# interests = set("Amusement Parks", "Animal Farms", "Animals", "Arcades", "Arts", "Arts & Crafts", "Arts and crafts", "Attraction Farms", "Axe Throwing", "Baking", "Baseball", "Basketball", "Billiard", "Boating", "Botanical Gardens", "Bounce Houses", "Bouncy castles", "Bowling", "Cake", "Cinema", "Climbing", "Coding", "Comedy", "Community Service", "Concerts", "Cooking", "Costumes", "Country", "Country Music", "Crafts", "Dancing", "disk jockey", "DJ", "drawing", "Escape Rooms", "Farm Stay", "Farms", "Games", "Gardens", "Go kart", "go karting", "Go-kart", "go-karting", "gokart", "Golf", "Gym", "Gymnasium", "Gymnastics", "Horse", "Horseback Riding", "ice rink", "Ice skating", "Indoor Skydiving", "Karaoke", "Magic", "Mini golf", "mini-golf", "minigolf", "Movie", "Museums", "Non-Profit", "Outdoor", "Outdoor Activities", "Paintball", "Painting", "Performing Arts", "Petting Zoos", "Photography", "Planetarium", "Plants", "Pool", "Programming", "Pumpkin Patches", "Race Tracks", "Riding", "Rock Climbing", "Roller Skating", "Science", "Shooting", "skating", "sketching", "Skydiving", "Softball", "Spa", "Spa saloon", "Sports", "Swimming", "swimming pool", "Theater", "Trampoline", "Trampoline Park", "Video Games", "Virtual Reality", "Virtual Reality Centers", "VR", "Water Park", "Water Sports", "Whale Watching", "Zoo")
interests = {'gymnastics', 'virtual reality centers', 'climbing', 'coding', 'pumpkin patches', 'painting', 'farms', 'minigolf', 'plants', 'basketball', 'pool', 'non-profit', 'whale watching', 'arcades', 'arts & crafts', 'go kart', 'amusement parks', 'go-karting', 'concerts', 'swimming', 'animal farms', 'outdoor activities', 'skating', 'theater', 'trampoline', 'vr', 'softball', 'photography', 'outdoor', 'museums', 'gym', 'country music', 'movie', 'cooking', 'dj', 'skydiving', 'magic', 'sports', 'ice rink', 'attraction farms', 'race tracks', 'spa saloon', 'horseback riding', 'arts and crafts', 'shooting', 'go karting', 'science', 'horse', 'escape rooms', 'riding', 'rock climbing', 'disk jockey', 'mini-golf', 'cinema', 'performing arts', 'farm stay', 'country', 'community service', 'paintball', 'roller skating', 'trampoline park', 'petting zoos', 'gardens', 'baseball', 'animals', 'mini golf', 'planetarium', 'ice skating', 'video games', 'games', 'programming', 'karaoke', 'bounce houses', 'dancing', 'bouncy castles', 'botanical gardens', 'comedy', 'go-kart', 'baking', 'golf', 'axe throwing', 'water park', 'spa', 'costumes', 'zoo', 'cake', 'gokart', 'water sports', 'crafts', 'boating', 'sketching', 'drawing', 'billiard', 'bowling', 'virtual reality', 'arts', 'gymnasium', 'swimming pool', 'indoor skydiving'}